# 1.Getting the system ready and loading the data

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
from collections import Counter

In [2]:
import pickle

# Reading data

In [3]:
train = pd.read_csv('E:/Project/train.csv')

In [4]:
test = pd.read_csv('E:/Project/test.csv')

# Missing value imputation

In [5]:
#missing data
total = train.isnull().sum().sort_values(ascending=False)
percent = (train.isnull().sum()/train.isnull().count()).sort_values(ascending=False)

 Fill Missing values by mode in Gender, Married, Dependents, Credit_History, and Self_Employed

In [6]:
train['Gender'].fillna(train['Gender'].mode()[0], inplace=True)
train['Married'].fillna(train['Married'].mode()[0], inplace=True)

train['Self_Employed'].fillna(train['Self_Employed'].mode()[0], inplace=True)
train['Credit_History'].fillna(train['Credit_History'].mode()[0], inplace=True)

In [7]:
# find  missing values in Loan_Amount_Term.

In [8]:
train['Dependents'].fillna(train['Dependents'].mode()[0], inplace=True)

In [9]:
train['Dependents'].mode()[0]

'0'

In [10]:
#value of 360 is repeating the 512 times so we  can fill missing value by mode

In [11]:
train['Loan_Amount_Term'].fillna(train['Loan_Amount_Term'].mode()[0], inplace=True)

In [12]:
# LoanAmount variabl is a numerical variable we can use mean or median to fill missing values
#loan amount has outliers instead of mean we can use median

In [13]:
train['LoanAmount'].fillna(train['LoanAmount'].median(), inplace=True)

In [14]:
#Check  here missing values are filled in the dataset.

In [15]:
train.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [16]:
total = train.isnull().sum().sort_values(ascending=False)
percent = (train.isnull().sum()/train.isnull().count()).sort_values(ascending=False)

In [17]:
# Lets fill all the missing values in the test dataset like train dataset
test['Gender'].fillna(train['Gender'].mode()[0], inplace=True)
test['Married'].fillna(train['Married'].mode()[0], inplace=True)

test['Self_Employed'].fillna(train['Self_Employed'].mode()[0], inplace=True)
test['Credit_History'].fillna(train['Credit_History'].mode()[0], inplace=True)
test['Loan_Amount_Term'].fillna(train['Loan_Amount_Term'].mode()[0], inplace=True)
test['LoanAmount'].fillna(train['LoanAmount'].median(), inplace=True)

In [18]:
test['Dependents'].fillna(train['Dependents'].mode()[0], inplace=True)

# Outlier Treatment

In [19]:
# lets  first consider how to remove  outliers of LoanAmount.
#bulk of the data in the loan amount is at the left and the right tail is longer. This is called right skewness.
#we can remove the skewness is by doing the log transformation

In [20]:
train['LoanAmount']=np.log(train['LoanAmount'])
test['LoanAmount']=np.log(test['LoanAmount'])

In [21]:
# Here distribution looks much closer to normal and the effect of extreme values has been significantly subsided.

#Skewness and kurtosis of Train Data

# Skewness and kurtosis of test data

# Remove skewness by power transformation

In [22]:
#*********************train  Data remove Skewness from LoanAmount *******************
from scipy.stats import boxcox
train['LoanAmount']=boxcox(train['LoanAmount'])[0]

In [23]:
#*********************Test Data remove Skewness from LoanAmount *******************
test['LoanAmount']=boxcox(test['LoanAmount'])[0]

In [24]:
#Logistic Regression is a classification algorithm
#Logistic Regression which is used for predicting binary outcome.
#It is used to predict a binary outcome (1 / 0, Yes / No, True / False) given a set of independent variables.
#Logistic regression is an estimation of Logit function. The logit function is simply a log of odds in favor of the event.
#This function creates an S-shaped curve with the probability estimate, which is very similar to the required stepwise function

In [25]:
# Loan_ID variable as it does not have any effect on the loan status.Remove it from train and test dataset

In [26]:
train=train.drop('Loan_ID',axis=1)
test=test.drop('Loan_ID',axis=1)

In [27]:
#drop our target variable from the training dataset and save it in another dataset.
# As Sklearn requires the target variable in a separate dataset.

In [28]:
X = train.drop('Loan_Status',1)
y = train.Loan_Status

In [29]:
train['Gender']=train.Gender.map({'Male':0,'Female':1})
train.Married=train.Married.map({'No':0,'Yes':1})
train.Education=train.Education.map({'Graduate':1,'Not Graduate':0})
train.Self_Employed=train.Self_Employed.map({'No':0,'Yes':1})
#train['Property_Area']=trainxzz

In [30]:
##train['Dependents']=train.Dependents.map({'1':1,'2':2,'3+':3})
#train['Property_Area']=train.Property_Area.map({'Urban':1,'Semiurban':2,'Rural':3})
train.head(50)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,0,0,1,0,5849,0.0,6.039031,360.0,1.0,Urban,Y
1,0,1,1,1,0,4583,1508.0,6.039031,360.0,1.0,Rural,N
2,0,1,0,1,1,3000,0.0,4.758102,360.0,1.0,Urban,Y
3,0,1,0,0,0,2583,2358.0,5.910652,360.0,1.0,Urban,Y
4,0,0,0,1,0,6000,0.0,6.232844,360.0,1.0,Urban,Y
5,0,1,2,1,1,5417,4196.0,7.553080,360.0,1.0,Urban,Y
6,0,1,0,0,0,2333,1516.0,5.452301,360.0,1.0,Urban,Y
7,0,1,3+,1,0,3036,2504.0,6.463061,360.0,0.0,Semiurban,N
8,0,1,2,1,0,4006,1526.0,6.588117,360.0,1.0,Urban,Y
9,0,1,1,1,0,12841,10968.0,8.127293,360.0,1.0,Semiurban,N
10,0,1,2,1,0,3200,700.0,4.868528,360.0,1.0,Urban,Y
11,0,1,2,1,0,2500,1840.0,5.720805,360.0,1.0,Urban,Y
12,0,1,2,1,0,3073,8106.0,6.946980,360.0,1.0,Urban,Y
13,0,0,0,1,0,1853,2840.0,5.809158,360.0,1.0,Rural,N
14,0,1,2,1,0,1299,1086.0,2.412458,120.0,1.0,Urban,Y
15,0,0,0,1,0,4950,0.0,5.991767,360.0,1.0,Urban,Y
16,0,0,1,0,0,3596,0.0,5.552077,240.0,1.0,Urban,Y
17,1,0,0,1,0,3510,0.0,5.023988,360.0,0.0,Urban,N
18,0,1,0,0,0,4887,0.0,6.115608,360.0,1.0,Rural,N
19,0,1,0,1,0,2600,3500.0,5.826405,360.0,1.0,Urban,Y
20,0,1,0,0,0,7660,0.0,5.628698,360.0,0.0,Urban,N
21,0,1,1,1,0,5955,5625.0,7.906147,360.0,1.0,Urban,Y
22,0,1,0,0,0,2600,1911.0,5.843517,360.0,0.0,Semiurban,N
23,0,1,2,0,0,3365,1917.0,5.774247,360.0,0.0,Rural,N
24,0,1,1,1,0,3717,2925.0,6.371143,360.0,1.0,Semiurban,N
25,0,1,0,1,1,9560,0.0,6.851701,360.0,1.0,Semiurban,Y
26,0,1,0,1,0,2799,2253.0,5.943460,360.0,1.0,Semiurban,Y
27,0,1,2,0,0,4226,1040.0,5.738766,360.0,1.0,Urban,Y
28,0,0,0,0,0,1442,0.0,3.611802,360.0,1.0,Urban,N
29,1,0,2,1,0,3750,2083.0,5.910652,360.0,1.0,Semiurban,Y
30,0,1,1,1,0,4166,3369.0,6.957322,360.0,1.0,Urban,N
31,0,0,0,1,0,3167,0.0,4.973433,360.0,1.0,Urban,N
32,0,0,1,1,1,4692,0.0,5.666012,360.0,1.0,Rural,N
33,0,1,0,1,0,3500,1667.0,5.809158,360.0,1.0,Semiurban,Y
34,0,0,3+,1,0,12500,3000.0,7.940014,360.0,1.0,Rural,N
35,0,1,0,1,0,2275,2067.0,6.039031,360.0,1.0,Urban,Y
36,0,1,0,1,0,1828,1330.0,5.552077,360.0,0.0,Urban,N
37,1,1,0,1,0,3667,1459.0,6.275249,360.0,1.0,Semiurban,Y
38,0,0,0,1,0,4166,7210.0,6.774705,360.0,1.0,Urban,Y
39,0,0,0,0,0,3748,1668.0,5.738766,360.0,1.0,Semiurban,Y
40,0,0,0,1,0,3600,0.0,5.121608,360.0,1.0,Urban,N
41,0,0,0,1,0,1800,1213.0,4.134324,360.0,1.0,Urban,Y
42,0,1,0,1,0,2400,0.0,4.998862,360.0,1.0,Urban,Y
43,0,1,0,1,0,3941,2336.0,6.130609,360.0,1.0,Semiurban,Y
44,0,1,0,0,1,4695,0.0,5.472630,360.0,1.0,Urban,Y
45,1,0,0,1,0,3410,0.0,5.304327,360.0,1.0,Urban,Y
46,0,1,1,1,0,5649,0.0,4.015842,360.0,1.0,Urban,Y
47,0,1,0,1,0,5821,0.0,6.275249,360.0,1.0,Urban,Y
48,1,1,0,1,0,2645,3440.0,5.910652,360.0,0.0,Urban,N
49,1,0,0,1,0,4000,2275.0,6.275249,360.0,1.0,Semiurban,Y

In [31]:
X = train[['Gender','Married','Education','Self_Employed','ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History']]
y = train.Loan_Status

X.shape
y.shape

In [32]:
#“Gender” variable. It has two classes, Male and Female.
#logistic regression takes only the numerical values as input
#“Gender” variable into two dummy  variables(Gender_Male and Gender_Female)
#Gender_Male= 0 if  gender = Female  and Gender_Male= 1 if gender= Male.

In [33]:
#X = pd.get_dummies(X)
#train=pd.get_dummies(train)
#test=pd.get_dummies(test)

In [34]:
#divide our train dataset in 2 parts : train and validation. 
#We can train the model on this training part and using that make predictions for the validation part.

In [35]:
from sklearn.model_selection import train_test_split
x_train, x_cv, y_train, y_cv = train_test_split(X,y, test_size=0.3)
#import LogisticRegression and accuracy_score from sklearn and fit the logistic regression model.
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import log_loss
model = LogisticRegression()
model.fit(x_train, y_train)
#predict the Loan_Status for validation set and calculate its accuracy.
pred_cv = model.predict(x_cv)

In [36]:
pickle_out=open('E:/Project/c1.pkl',mode='wb')
pickle.dump(model,pickle_out)
pickle_out.close()